v0.2 + Source connection status: /etc/chrome-update/date_stamp

diff --git a/all/etc/chrome-update/chrome-update b/all/etc/chrome-update/chrome-update
--- a/all/etc/chrome-update/chrome-update
+++ b/all/etc/chrome-update/chrome-update
@@ -20,7 +20,16 @@ if [ -n "$(grep chrome_x86_64 /etc/urpmi/urpmi.cfg)" ]; then
     urpmi.removemedia chrome_x86_64
 fi
 
+#Подключить источник
 urpmi.addmedia chrome_x86_64 http://dl.google.com/linux/chrome/rpm/stable/x86_64
+
+#Статус подключения источника: штамп даты или error
+if [ "$?" -eq "0" ]; then
+    date '+%d-%m-%Y' > /etc/chrome-update/date_stamp
+	else
+    echo "Connecting the repository: ERROR" > /etc/chrome-update/date_stamp
+    exit 1
+fi
 
 #Форсированная установка браузера
 urpmi --force google-chrome-stable
@@ -29,7 +38,5 @@ urpmi --force google-chrome-stable
 if [ -n "$(grep chrome_x86_64 /etc/urpmi/urpmi.cfg)" ]; then
     urpmi.removemedia chrome_x86_64
 fi
-
-date '+%d-%m-%Y' > /etc/chrome-update/date_stamp
 
 exit 0;
